name = "Cave"
description = "a comfy room with sofas and a tv"

[[contents]]
name = "tv"
description = "Hackers has to run for the thousandth time now"

[[contents]]
kind = "item"
name = "tv remote"
description = "the batteries seem to have died"

[[contents]]
kind = "gateway"
name = "door"
description = "there's a drawing of Xenia the fox on it"
target = "lounge"
