name = "Cave"
description = "a comfy room with sofas and a tv"

[[contents]]
name = "tv"
description = "Hackers has to run for the thousandth time now"

[[contents]]
kind = "item"
name = "tv remote"
description = "the batteries seem to have died"
